-- MySQL Script generated by MySQL Workbench
-- Thu Oct  5 08:47:11 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kasir
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kasir
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kasir` DEFAULT CHARACTER SET utf8 ;
USE `kasir` ;

-- -----------------------------------------------------
-- Table `kasir`.`jenis_barang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kasir`.`jenis_barang` (
  `id_jenis_barang` INT(11) NOT NULL,
  `nama_jenis_barang` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_jenis_barang`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kasir`.`barang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kasir`.`barang` (
  `id_barang` INT(11) NOT NULL,
  `nama_barang` VARCHAR(45) NULL DEFAULT NULL,
  `harga_jual_barang` VARCHAR(45) NULL DEFAULT NULL,
  `id_jenis_barang` INT NULL DEFAULT NULL,
  `harga_beli_barang` VARCHAR(45) NULL,
  PRIMARY KEY (`id_barang`),
  INDEX `id_jenis_barang_idx` (`id_jenis_barang` ASC),
  CONSTRAINT `id_jenis_barang`
    FOREIGN KEY (`id_jenis_barang`)
    REFERENCES `kasir`.`jenis_barang` (`id_jenis_barang`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kasir`.`pelanggan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kasir`.`pelanggan` (
  `id_pelanggan` INT(11) NOT NULL,
  `nama_pelanggan` VARCHAR(255) NULL DEFAULT NULL,
  `alamat_pelanggan` VARCHAR(255) NULL DEFAULT NULL,
  `cp_pelanggan` VARCHAR(12) NULL DEFAULT NULL,
  PRIMARY KEY (`id_pelanggan`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kasir`.`pegawai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kasir`.`pegawai` (
  `id_pegawai` INT(11) NOT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `nama_pegawai` VARCHAR(255) NULL DEFAULT NULL,
  `alamat_pegawai` VARCHAR(255) NULL DEFAULT NULL,
  `akses_pegawai` VARCHAR(45) NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_pegawai`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kasir`.`faktur_penjualan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kasir`.`faktur_penjualan` (
  `id_faktur` INT(11) NOT NULL,
  `no_faktur` INT NULL DEFAULT NULL,
  `tanggal_penjualan` DATE NULL DEFAULT NULL,
  `id_barang` INT(11) NULL DEFAULT NULL,
  `jumlah_barang` INT(11) NULL DEFAULT NULL,
  `total_bayar` INT(11) NULL DEFAULT NULL,
  `kembali` INT(11) NULL DEFAULT NULL,
  `id_pelanggan` INT(11) NULL DEFAULT NULL,
  `id_pegawai` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_faktur`),
  INDEX `id_barang_idx` (`id_barang` ASC),
  INDEX `no_faktur` (`no_faktur` ASC),
  INDEX `id_pelanggan_idx` (`id_pelanggan` ASC),
  INDEX `id_pegawai_idx` (`id_pegawai` ASC),
  CONSTRAINT `id_barang`
    FOREIGN KEY (`id_barang`)
    REFERENCES `kasir`.`barang` (`id_barang`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_pelanggan`
    FOREIGN KEY (`id_pelanggan`)
    REFERENCES `kasir`.`pelanggan` (`id_pelanggan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_pegawai`
    FOREIGN KEY (`id_pegawai`)
    REFERENCES `kasir`.`pegawai` (`id_pegawai`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kasir`.`detail_penjualan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kasir`.`detail_penjualan` (
  `id_detail_penjualan` INT(11) NOT NULL,
  `no_faktur` INT(11) NULL DEFAULT NULL,
  `jumlah_penjualan` VARCHAR(10) NULL DEFAULT NULL,
  `jadwal_pengiriman` DATETIME NULL DEFAULT NULL,
  `tanggal_pengiriman` DATETIME NULL DEFAULT NULL,
  `ongkos_kirim` VARCHAR(45) NULL,
  PRIMARY KEY (`id_detail_penjualan`),
  INDEX `no_faktur_idx` (`no_faktur` ASC),
  CONSTRAINT `no_faktur`
    FOREIGN KEY (`no_faktur`)
    REFERENCES `kasir`.`faktur_penjualan` (`no_faktur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kasir`.`stok_barang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kasir`.`stok_barang` (
  `id_stok_barang` INT(11) NOT NULL,
  `tanggal_update` DATETIME NULL DEFAULT NULL,
  `id_barang` INT(11) NULL DEFAULT NULL,
  `id_pegawai` INT(11) NULL DEFAULT NULL,
  `stok_barang` INT NULL,
  PRIMARY KEY (`id_stok_barang`),
  INDEX `id_barang_idx` (`id_barang` ASC),
  INDEX `id_pegawai_idx` (`id_pegawai` ASC),
  CONSTRAINT `id_barang`
    FOREIGN KEY (`id_barang`)
    REFERENCES `kasir`.`barang` (`id_barang`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_pegawai`
    FOREIGN KEY (`id_pegawai`)
    REFERENCES `kasir`.`pegawai` (`id_pegawai`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
